## Tutorial to compute *Elemenatry Effects*

This tutorial is based on the the 1991 Article by Max D. Morris (Factorial Sampling Plans for Preliminary Computational Experiments $Technometrics$, Vol. 33, No. 2 (May, 1991), pp. 161-174.)

Stable URL:
http://links.jstor.org/sici?sici=0040-1706%28199105%2933%3A2%3C161%3AFSPFPC%3E2.0.CO%3B2-N 

Technometrics is currently published by American Statistical Association.


In [1]:
import numpy as np

## Key concepts

1. A large (absolute) measure of central tendency (e.g. mean) for $F_i$ indicates that such input $x_i$ has an important overalll influence on the output $y$.

2. A large measure of spread (e.g. standard deviation) for $F_i$ indicates an input $x_i$ whose influence is highly dependent on the values of other inputs $x_j$ (i.e., one inolved with interations or with non-linear effects).  

3. Economy of design can be improved if some runs are used in computing more than one elementary effect (in effect, changing two parameters simultaneously). In such a case it is convenient to impose the following restrictions:

    $p$ is even; and

    $\Delta = p/(2(p-1)$

## Assumptions

In [62]:
p = 4
delta = p/(2*(p-1))

In [61]:
delta

0.6666666666666666

## Definitions

$\omega = $ region of experimentation, which is a regular $k$-dimensional (i.e. number of parameters to test), $p$-level grid (possible values), and where $x_i$:  

$x_i = \{0, 1/(p-1), 2/(p-1),.., 1\}$

Note that $p$ is the length of the $x_i$ vector containing the possible values that $x_i$ can take when building the **base vector**. 

Distribution (or total number) of *elementary effects* for each parameter $x_i$ is:

$F_i = p^{k-1}[p-\Delta(p-1)]$

## Steps

### 1. Basic design

Select an $m-by-k$ sampling matrix ($m = k+1$), **B**, with elements that are 0's and 1's, with the property that for every column $i=1,2,3,..,k$ there are two rows of **B** that differ only in their $ith$ entries: 

In [6]:
B = np.matrix([[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 1, 1]])

In [7]:
B

matrix([[0, 0, 0],
        [1, 0, 0],
        [1, 1, 0],
        [1, 1, 1]])

$\Delta$**B** could be used as a design matrix (i.e., each row a value of **x**), for which the experiment would provide $k$ elementary effects, one for each input based **only on *k+1* runs**.

### Step 2. Produce a randomized version of the design matrix.

- Let **D\*** be a $k-dimensional$ diagonal matrix in which each each diagonal element is either +1 or -1 with equal probability.

In [46]:
k=3
vec=np.random.choice([-1,1],k)
D=np.diag(vec)

In [47]:
D

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

Let **J$_{m,k}$** be the $m-by-k$ matrix of 1's:

In [41]:
m = k + 1
J = np.ones((m,k))

In [43]:
J

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Let **S** be a randomized sample matrix for the original sampling design matrix **B**, where:

$S = \frac{1}{2}[(2B-J_{m,k})D^*+J_{m,k}]$ 

In [52]:
S = (1/2)*((2*B-J)*D+J)

In [53]:
S

matrix([[ 1.,  0.,  1.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]])

### Step 3. Select a random base vector **x**. 

Let **x\*** be a randomly chosen "base value" of **x** for each element is randomly assigned a value from $x_i=\{0, 1/(p-1), 2/(p-1), ...,1-\Delta\}$

In [70]:
xi = []
for i in range(p):
    xi.append(i/(p-1))
xi

[0.0, 0.3333333333333333, 0.6666666666666666, 1.0]

## Questions

### General

1. Is knowing what a unit hypercube necessary?

### Random  Sampling

1. The mean for $F_i$ is drawn by changing the parameter $x_i$ only by $\Delta$ while changing (or not) other parameters $x_j$ (also by $\Delta$).

From this I understand that we cannot derive information of the exact effect of parameter $x_i$ on $y$, but rather the mean effect of $x_i$ on $y$. 

To calculate $F_i$ one would need to extract all the runs where and elementary effect was obtained by adding $\Delta$ to $x_i$, while excluding all other runs where $x_i$ did not change from the base vector. 
